### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by zpatten** [Atalanta/cucumber-chef#101]
OK; so the gem needs to be eliminated from the test lab ASAP.  I have been planning this for a while actually, but I had to do a lot of leg work to get there.  Given the recent dependency issues; having to shove the gem onto the test lab only complicates things.

I know what needs to happen in the code to pull this off; it's not going to be that hard now that I've re-wired a lot of the other internals.  My plan is to tackle this over this coming weekend.

Another thing I wish to tackle this weekend will be building the RSpec hooks so that you can dual purpose and run either Cucumber or RSpec tests.

**Comment by zpatten** [comment]
Also; I have been running cucumber-chef now with Jenkins/Janky if anyone is interested.

**Comment by pikesley** [comment]
Ooh yes please on Jenkins! Tell us more...
