### ISSUE TITLE
Calling cucumber-chef setup invokes the ip method with the extra :ip argument.

### ISSUE THREAD

**Issue by edyu** [Atalanta/cucumber-chef#118]
I'm following the book example and this is what shows up. I originally tried to fix it by removing :ip and :port from super(:ip) and super(:port) but that still didn't fix the problem as it now hangs.

/Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/cucumber-chef-3.0.5/lib/cucumber/chef/providers/aws.rb:191:in `ip': wrong number of arguments (1 for 0) (ArgumentError)
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/cucumber-chef-3.0.5/lib/cucumber/chef/provider.rb:86:in`method_missing'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/cucumber-chef-3.0.5/lib/cucumber/chef/provider.rb:75:in `ip'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/cucumber-chef-3.0.5/lib/cucumber/chef/test_lab.rb:108:in`method_missing'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/cucumber-chef-3.0.5/lib/cucumber/chef/test_lab.rb:45:in `bootstrap_ssh'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/cucumber-chef-3.0.5/lib/cucumber/chef/provisioner.rb:74:in`block in upload_chef_repo'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/ztk-1.0.10/lib/ztk/benchmark.rb:107:in `block (2 levels) in bench'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/ztk-1.0.10/lib/ztk/spinner.rb:76:in`spin'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/ztk-1.0.10/lib/ztk/benchmark.rb:106:in `block in bench'
    from /Users/ed/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/benchmark.rb:295:in`realtime'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/ztk-1.0.10/lib/ztk/benchmark.rb:103:in `bench'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/cucumber-chef-3.0.5/lib/cucumber/chef/provisioner.rb:61:in`upload_chef_repo'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/cucumber-chef-3.0.5/lib/cucumber/chef/provisioner.rb:45:in `build'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/cucumber-chef-3.0.5/bin/cucumber-chef:94:in`setup'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/thor-0.18.1/lib/thor/invocation.rb:120:in`invoke_command'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/thor-0.18.1/lib/thor/base.rb:439:in`start'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/gems/cucumber-chef-3.0.5/bin/cucumber-chef:545:in `<top (required)>'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/bin/cucumber-chef:19:in`load'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/bin/cucumber-chef:19:in `<main>'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/bin/ruby_noexec_wrapper:14:in`eval'
    from /Users/ed/.rvm/gems/ruby-1.9.3-p374@chef/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by zpatten** [comment]
Duplicate of https://github.com/Atalanta/cucumber-chef/issues/112

**Comment by zpatten** [comment]
OK I've released v3.0.6 of the gem; this issue should now be resolved; please let me know.

**Comment by edyu** [comment]
This particular issue seems to be fixed. Thank you! I'll let you know if I encounter any other issues.

**Comment by zpatten** [comment]
Awesome!  Glad to hear!
