### ISSUE TITLE
Cucumber loads all .rb files and blows up

### ISSUE THREAD

**Issue by edyu** [Atalanta/cucumber-chef#121]
This is somewhat similar to issue #88. 
At first it was complaining about cookbooks/users/meta.rb and then after adding and modifying cucumber.yml to ignore cookbooks directory, it complains about environments/production.rb. I'm certain it will complain about a lot of files.

**Comment by edyu** [comment]
Here is the output

cucumber test teamserver        [~/dev/chef/cucumber-chef]
Using the default profile...
Code:
- ./features/support/env.rb
- ./features/support/cc-hooks.rb
  >>> cucumber-chef v3.0.7
  >>> Pushing chef-repo environments to the test lab completed in 1.3196 seconds.
  >>> Pushing chef-repo cookbooks to the test lab completed in 1.5174 seconds.
  >>> Pushing chef-repo roles to the test lab completed in 0.8102 seconds.
  >>> Pushing chef-repo data bag 'users' to the test lab completed in 1.5163 seconds.
  >>> Creating container 'teamserver-app-1' completed in 2.1473 seconds.
  >>> Provisioning container 'teamserver-app-1' completed in 19.7982 seconds.
- ./LICENSE [NOT SUPPORTED]
- ./Labfile [NOT SUPPORTED]
  Failed to load 'md' programming language for file ./README.md: cannot load such file -- cucumber/md_support/md_language
- ./README.md [NOT SUPPORTED]
- ./Rakefile [NOT SUPPORTED]
- ./certificates/README.md [NOT SUPPORTED]
- ./chefignore [NOT SUPPORTED]
- ./config/rake.rb
  Failed to load 'yml' programming language for file ./cucumber.yml: cannot load such file -- cucumber/yml_support/yml_language
- ./cucumber.yml [NOT SUPPORTED]
- ./data_bags/README.md [NOT SUPPORTED]
  Failed to load 'json' programming language for file ./data_bags/users/cucumber-chef.json: cannot load such file -- cucumber/json_support/json_language
- ./data_bags/users/cucumber-chef.json [NOT SUPPORTED]
- ./environments/README.md [NOT SUPPORTED]
- ./environments/production.rb
  undefined method `name' for main:Object (NoMethodError)
  /Users/ed/dev/chef/cucumber-chef/environments/production.rb:1:in`<top (required)>'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/gems/cucumber-1.2.5/lib/cucumber/rb_support/rb_language.rb:137:in `load'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/gems/cucumber-1.2.5/lib/cucumber/rb_support/rb_language.rb:137:in`load_code_file'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/gems/cucumber-1.2.5/lib/cucumber/runtime/support_code.rb:180:in `load_file'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/gems/cucumber-1.2.5/lib/cucumber/runtime/support_code.rb:83:in`block in load_files!'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/gems/cucumber-1.2.5/lib/cucumber/runtime/support_code.rb:82:in `each'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/gems/cucumber-1.2.5/lib/cucumber/runtime/support_code.rb:82:in`load_files!'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/gems/cucumber-1.2.5/lib/cucumber/runtime.rb:182:in `load_step_definitions'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/gems/cucumber-1.2.5/lib/cucumber/runtime.rb:41:in`run!'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/gems/cucumber-1.2.5/lib/cucumber/cli/main.rb:43:in `execute!'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/gems/cucumber-1.2.5/lib/cucumber/cli/main.rb:20:in`execute'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/gems/cucumber-1.2.5/bin/cucumber:14:in `<top (required)>'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/bin/cucumber:19:in`load'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/bin/cucumber:19:in `<main>'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/bin/ruby_noexec_wrapper:14:in`eval'
  /Users/ed/.rvm/gems/ruby-1.9.3-p392@chef/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by edyu** [comment]
---

default: --color --verbose --backtrace --exclude cookbooks --exclude environments --exclude roles --exclude support/cookbooks --exclude support/data_bags --exclude support/environments --exclude support/keys --exclude support/roles --format pretty

**Comment by edyu** [comment]
It's now complaining about create_server() call which I assume should've been part of a helper for chef but I can't find it.
At this point, I'm giving up on getting the book to work. The book doesn't complete the full steps on what I need to do so I can't reverse-engineer what needs to be done. :(

**Comment by edyu** [comment]
I created it. See 2 comments back. But at this point, it's not cucumber-chef anymore but I can't go on with the instruction (or the lack of) on the book. :( I can't figure out where create_server is defined and it was supposed to work by putting in the steps file.

**Comment by zpatten** [comment]
Ya I'm not sure what's going on here; something is broken thou.

You will not be able to follow the directions in the book with the latest version.  It flat out won't work.

I suggest reading the WIKI.md and 2.x WIKI.md from the cucumber-chef repo.

**Comment by zpatten** [comment]
Again; I would suggest following the directions in my `cc-chef-repo` and using that as a starting point.

**Comment by zpatten** [comment]
Between that; the WIKI.md files in the cucumber-chef repo root and the book; it should be somewhat obvious how things work now.
