### ISSUE TITLE
Can cucumber-chef be used without AWS?

### ISSUE THREAD

**Issue by mrjcleaver** [Atalanta/cucumber-chef#125]
(I was directed here from the #cucumber-chef irc channel)

What's AWS used for?

I have plenty of computing resources locally, no need or want to pay for an AWS account. 

Thanks, M.

**Comment by zpatten** [comment]
AWS is available as a provider, along with Vagrant.  They are mutually exclusive.

When doing integration testing through CI; it is often best to use AWS to avoid running Vagrant/VirtualBox on your Jenkins nodes for example.  

As such companies I've worked with tend to use AWS backed testlabs for CI purposes and Vagrant/VirtualBox backed testlabs for development purposes.
