### ISSUE TITLE
cucumber-chef will not gem install without dependency force

### ISSUE THREAD

**Issue by hinder90** [Atalanta/cucumber-chef#18]
mlitwin@ubuntu:~$ gem install cucumber
Fetching: gherkin-2.4.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: term-ansicolor-1.0.5.gem (100%)
Fetching: diff-lcs-1.1.2.gem (100%)
Fetching: cucumber-1.0.0.gem (100%)

(::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::)

Thank you for installing cucumber-1.0.0.
Please be sure to read http://wiki.github.com/cucumber/cucumber/upgrading
for important information about this release. Happy cuking!

(::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::) (::)

Successfully installed gherkin-2.4.1
Successfully installed term-ansicolor-1.0.5
Successfully installed diff-lcs-1.1.2
Successfully installed cucumber-1.0.0
4 gems installed
Installing ri documentation for gherkin-2.4.1...
Installing ri documentation for term-ansicolor-1.0.5...
Installing ri documentation for diff-lcs-1.1.2...
Installing ri documentation for cucumber-1.0.0...
Installing RDoc documentation for gherkin-2.4.1...
Installing RDoc documentation for term-ansicolor-1.0.5...
Installing RDoc documentation for diff-lcs-1.1.2...
Installing RDoc documentation for cucumber-1.0.0...

mlitwin@ubuntu: gem install cucumber-chef
ERROR:  Error installing cucumber-chef:
  cucumber-chef requires cucumber-chef (>= 0)

mlitwin@ubuntu: gem --version
1.6.2

mlitwin@ubuntu:~$ rvm --version

rvm 1.6.20 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]

mlitwin@ubuntu:~$ ruby --version
ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-linux]

mlitwin@ubuntu:~$ gem install cucumber-chef --ignore-dependencies
Successfully installed cucumber-chef-1.0.2
1 gem installed
Installing ri documentation for cucumber-chef-1.0.2...
Installing RDoc documentation for cucumber-chef-1.0.2...

**Comment by umairsiddique** [comment]
I'm having the same problem.

Removing this line might help.
https://github.com/Atalanta/cucumber-chef/blob/master/cucumber-chef.gemspec#L90

**Comment by Atalanta** [comment]
This is proving to much less trivial than I'd hoped.  The gem installs, but tests are failing in unexpected ways.  Working on getting tests passing.  This won't be fixed before Monday - sorry.

**Comment by Atalanta** [comment]
Fixed in 1.0.3
