### ISSUE TITLE
Ability to set default AWS image id in knife.rb

### ISSUE THREAD

**Issue by ghost** [Atalanta/cucumber-chef#2]
Currently the TestLab is built using ami-339ca947 which is only available in Amazon's eu-west-1 region. I would like to propose pulling the default image a user would like to use from the .chef/knife.rb file as well using a variable like @config[:knife][image_id]

**Comment by ghost** [comment]
Will fork and issue a pull request today.

**Comment by Atalanta** [comment]
Fixed in 1.0.1.
