### ISSUE TITLE
Allow instance type to be specified

### ISSUE THREAD

**Issue by SFEley** [Atalanta/cucumber-chef#21]
We have some recipes for services like Mongo that assume a 64-bit architecture.  Because Chef-Cucumber hardcodes to an `m1.small` type, they can't be tested without some workarounds.  I'd like the ability to specify an instance type and an AMI that would work on a `t1.micro` or `m1.large` instance.

**Comment by alexm** [comment]
+1 for being able to specify instance type; `m1.micro` is cheaper and may even be free the first year.
