### ISSUE TITLE
Request: documentation and step definitions

### ISSUE THREAD

**Issue by SFEley** [Atalanta/cucumber-chef#22]
Hi.  So I've bought your O'Reilly book and I'm trying to put Cucumber-Chef to work as described.  However, I'm having a hard time finding useful references apart from the book's limited examples.  Specific concerns:
1. The API for the Cucumber::Chef module seems to be undocumented. There's no RDoc, and in looking at the code, it's hard to tell which methods are intended to be used by command line tools and which are "helper" methods to be used by end users within Cucumber steps. Am I missing some core reference that will tell me how to use this code inside features?
2. Outside the couple in the book, I can't find any working step definitions.  The example feature doesn't even provide them -- all of the step definitions are "pending."  This doesn't make sense -- if the example itself can't run, what is it supposed to demonstrate?  A working, _implemented_ example would be much more useful for setup confirmation and for learning. A library of working step definitions for common tasks would also be reasonable to include in the gem. (Or at the very least, in the gem's Github wiki.)
3. The http://cucumber-chef.org Web site is incomplete.  In fact, it seems to trail off in mid-section while describing setup.  And the "Docs" tab at top isn't a link.

Again, if there's anyplace else I can look for help on how to get Cucumber-Chef running, please let me know.  You've versioned the gem at 1.0 (universally understood to be "production-ready") _and_ you've published a book about it.  Given that expectations you've set about this tool's maturity, I don't think it's unreasonable to assert that basic usage information ought to exist _somewhere_ and be readily discoverable.

**Comment by danicuki** [comment]
The idea of cucumber-chef is excellent and very valuable. But I must agree with SFEley, there are some missing points. I also had a lot of problems to follow the examples in the book, once most of them doesn't work properly.

If you need some help to improve this tool, I'm available!

**Comment by Atalanta** [comment]
We have some updated info to add to the wiki - will do that in the next few day (ideally by the end of next week).

danicuki - sorry for the slow response - we're now actively working on this - if you're interested in helping still, please say.

**Comment by zpatten** [comment]
The README now has mucho grande examples.

If you are still experiencing issues with this please re-open this issue; I am closing this for now since it has become stale.
