### ISSUE TITLE
Cucumber and Cucumber-Nagios should be runtime dependencies

### ISSUE THREAD

**Issue by SFEley** [Atalanta/cucumber-chef#24]
The `cucumber-chef.gemspec` (v1.0.3) executes the following dependency statements when Rubygems higher than 1.2 is used:

```
  s.add_runtime_dependency(%q<rake>, ["~> 0.9.2"])
  s.add_runtime_dependency(%q<chef>, [">= 0.10.2"])
  s.add_runtime_dependency(%q<fog>, [">= 0"])
  s.add_runtime_dependency(%q<thor>, [">= 0"])
  s.add_runtime_dependency(%q<net-scp>, [">= 0"])
  s.add_development_dependency(%q<cucumber>, [">= 0"])
  s.add_development_dependency(%q<cucumber-nagios>, [">= 0"])
  s.add_development_dependency(%q<rspec>, [">= 0"])
  s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
  s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
  s.add_development_dependency(%q<rcov>, [">= 0"])
```

Cucumber and Cucumber-Nagios are declared as _development_ dependencies, meaning they're not installed in a simple `gem install cucumber-chef` call.  This would make sense for some use cases, but for Cucumber-Chef these are very much _runtime_ dependencies, required by the gem's core function.  They should be declared as such so that they're installed alongside the gem.  

(I already had Cucumber on my system, but ran into a _"no such file to load -- cucumber/nagios/steps (LoadError)"_ on first test invocation.)

**Comment by wiremine** [comment]
FWIW, just to add to this a bit: I was working my way through the new Cucumber Chef book, and I ran into issues getting cucumber and chef to play nice. The book aludes to using cucumber to generate templates (although it doesn't give the details of running the command, which was frustrating). So, +1 on requiring cucumber as a dependency, and explicitly setting the version for both chef and cucumber

**Comment by leinster** [comment]
Fixed in [e05be0](https://github.com/Atalanta/cucumber-chef/commit/e05be0e359df8633b2fcec1e9e71047f283c55bc)
