### ISSUE TITLE
Cucumber-Nagios not installed on remote nodes

### ISSUE THREAD

**Issue by SFEley** [Atalanta/cucumber-chef#25]
The project generator includes a dependency on `cucumber/nagios/steps` in the **support/env.rb** file.  I'm not sure whether this is critical to Cucumber-Chef's operation, but I was loath to take it out.  However, it causes `cucumber test` runs to fail, because the cookbook uploaded to the test lab doesn't install the **cucumber-nagios** gem.

I'm sending a pull request that fixes this and other issues.

**Comment by danicuki** [comment]
I've got into the same problem. Hope you Pull Request get accepted soon

Thanks!!!

Daniel

**Comment by leinster** [comment]
Fixed by https://github.com/Atalanta/cucumber-chef/pull/26, thanks.
