### ISSUE TITLE
book p34 - identity_file + aws_ssh_key_id not mentioned before

### ISSUE THREAD

**Issue by drnic** [Atalanta/cucumber-chef#28]
In the book on p34, we're told to add the following to knife.rb:

``` ruby
knife[:identity_file] = "/path/to/my/id_rsa-ec2"
knife[:aws_ssh_key_id] = ENV['AWS_SSH_KEY_ID']
```

I don't think there is any mention in the book for how to generate `id_rsa-ec2` (nothing appears in a search of the PDF except page 34) nor what value $AWS_SSH_KEY_ID might be.

The only mention of SSH keys is when setting up GitHub on page 20.

Assuming I make my keys with:

```
ssh-keygen -t rsa -f ~/.ssh/id_rsa-ec2
```

What is $AWS_SSH_KEY_ID?

**Comment by kashif** [comment]
As far as I know, the `knife[:identify_file] = "/Users/kashif/.ssh/key.pem"` points to the downloaded `.pem` you get when you generate a new _Key Pair_ via the amazon EC2 console page.

The `knife[:aws_ssh_key_id] = "key"` is the name you gave this specific key pair.

Hope this helps.

**Comment by drnic** [comment]
So "key" is the same value?

**Comment by drnic** [comment]
And would you put the key.pem (which I called "drnic-eu-west-1" and hence the .pem is "drnic-eu-west-1.pem") in ~/.chef?

**Comment by drnic** [comment]
Does the following look correct?

``` ruby
current_dir = File.dirname(__FILE__)
user = ENV['OPSCODE_USER'] || ENV['USER']
log_level :info
log_location STDOUT
node_name user
client_key "#{ENV['HOME']}/.chef/#{user}.pem"
validation_client_name "#{ENV['ORGNAME']}-validator"
validation_key "#{ENV['HOME']}/.chef/#{ENV['ORGNAME']}-validator.pem"
chef_server_url "https://api.opscode.com/organizations/#{ENV['ORGNAME']}"
cache_type 'BasicFile'
cache_options( :path => "#{ENV['HOME']}/.chef/checksums" )
cookbook_path ["#{current_dir}/../cookbooks"]

knife[:aws_access_key_id]     = ENV['AWS_ACCESS_KEY_ID'] || Fog.credentials[:aws_access_key_id]
knife[:aws_secret_access_key] = ENV['AWS_SECRET_ACCESS_KEY'] || Fog.credentials[:aws_secret_access_key]
knife[:aws_ssh_key_id] = ENV['AWS_SSH_KEY_ID'] || user
knife[:identity_file] = "#{ENV['HOME']}/.chef/#{user}.pem"
knife[:availability_zone] = "eu-west-1a"
knife[:region] = "eu-west-1"
knife[:aws_image_id] = "ami-339ca947"
```

It is giving me the error at the bottom of #29 (sorry that the same error is now referenced in two issues)

**Comment by kashif** [comment]
Yes the location of the `.pem` files does not matter & as far as I see and your `knife.rb` looks ok. Another thing sometimes people miss is to `chmod` the `.pem` file to `chmod 600 *.pem`. Hope this helps.

**Comment by Atalanta** [comment]
This needs better documentation.  We'll update that and make the step-by-step instructions are clearer.

**Comment by zpatten** [comment]
If you are still experiencing issues with this please re-open this issue; I am closing this for now since it has become stale.
