### ISSUE TITLE
Support test lab environments based on distros other than Ubuntu

### ISSUE THREAD

**Issue by ghost** [Atalanta/cucumber-chef#4]
lib/cucumber/chef/test_runner.rb  will need some changes for non-Ubuntu based distros (i.e. different home dirs, ssh unames, etc). Will work this weekend on a fork that determines distro type from image-id and executes run() and upload_project() appropriately.

**Comment by Atalanta** [comment]
How are you getting on with this?  Just trying to prioritize development effort.  I agree this is an important feature.

**Comment by ghost** [comment]
Pretty close to being done. I will get a pull request over to you late Monday or at the latest Tuesday.

**Comment by justinsaul** [comment]
+1 for this feature. I believe this is important for enterprise adoption.

**Comment by Atalanta** [comment]
Hi - are you still interested in helping make this happen?  Our next target is CentOS 6 and then CentOS 5.

**Comment by zpatten** [comment]
As of the latest RC build; we can do Fedora as well as Ubuntu containers currently.  As Stephen states above; CentOS is our next target as far as LXC flavors go.
