### ISSUE TITLE
instance-id not found

### ISSUE THREAD

**Issue by cgriego** [Atalanta/cucumber-chef#42]
Looks like there's a race condition in the provisioning. I got an error saying that the instance-id was not found, but when I looked in the EC2 console, there it was. I suspect that cucumber-chef issued the api call to boot the instance, and Amazon's API response was eventually consistent. cucumber-chef should retry with a timeout to find the instance data.

**Comment by Atalanta** [comment]
We're confident that this is fixed in the RC, which honors the new ubuntu-ami gem's behavior.
