### ISSUE TITLE
cucumber-chef setup hanging

### ISSUE THREAD

**Issue by alex-ethier** [Atalanta/cucumber-chef#44]
I'm trying to setup cucumber-chef and I'm having some issues.

cucumber-chef setup

Provisioning cucumber-chef test lab platform.
Waiting for server................
Instance ID: i-xxxxxxxx ; IP Address xxx.xxx.xxx.xxx
Platform provisioned.  Run cucumber-chef project to get started.

I left the setup process running for 1 hour and it still wasn't done.

I don't see the node in my hosted chef console.

Is there a way to see what's happening during the setup? (--verbose, --trace, log?)

Anyone having this problem?
A

**Comment by Atalanta** [comment]
This is fixed in the RC.
