### ISSUE TITLE
aws_security_group not "working"

### ISSUE THREAD

**Issue by ghost** [Atalanta/cucumber-chef#45]
Hi,
Am I the only one that has this problem?

I specify a security group in my knife config with :
knife[:aws_security_group] = "my-existing-security-group"

but the instance created by cucumber chef is always default..
A

**Comment by N3SS4** [comment]
what version of the gem do you have? i don't think the lastet gem (1.0.3) has the security group option because it's from june or july and the option was added after that. You probably need to build from source.

**Comment by Atalanta** [comment]
This will work in the RC.
