### ISSUE TITLE
Need maintainers? (for issues/wiki)

### ISSUE THREAD

**Issue by patcon** [Atalanta/cucumber-chef#47]
Hey Stephen! Had a quick exchange with you on Twitter, and just wanted to follow up.

I don't know if I knowledgeable enough at the moment to take a frontline role on the code, but if it's alright with you, I wouldn't mind helping to organize the issue queues and wiki. Just thinking aggregating features requests and maybe a rough roadmap.

Seems that the opscode guys are starting to thinking about version-controlling tests with community cookbooks, so I'm trying to get a feel for which framework/approach works best. Really like the system you've got going :)

**Comment by Atalanta** [comment]
Help would be great. I've been rather busy so have neglected this, but it's very much a live project, and I have lots of ideas.  Organising and prioritising bugs and feature requests would be superb.

There's an IRC channel - although right now it's very quiet.  There's also a mailing list.

In terms of help, what I need more than anything is someone prepared to take on a release manager kind of role - ie periodically aggregate bug fixes and update the gem and release it.  If you feel you could do that, or if anyone else does, let me know and I'll grant access.

**Comment by zpatten** [comment]
Until I saw this latest activity I had figured the project was dead.  I'm currently in the process of doing some major updating of the code to bring it in line with more up to date versions of gems; including completely removing jeweler among other things.  As is I have yet to push any more changes to my repo since I am working through various issues still.  I'm willing to perform the release manager tasks in addition to the major changes I would ultimately like to bring to this project.  Please note what is in my public repo is broken at this point so it isn't even worth playing with for the moment.  I definitely have my own designs for this type of a system so if you are interested please ping me and we can talk further.  Otherwise I plan on splitting off my own "flavor" of cucumber-chef.

**Comment by patcon** [comment]
Sounds like you're a much better candidate -- was unsure how fitting I'd be since I haven't dug into the guts, and I still feel like a totally rookie programmer

**Comment by zpatten** [comment]
I'm sure to some that could be up for debate so don't let me discourage you from contributing as well, additionally I'm pretty busy with work as I imagine Stephen is.  I can give this a lot of attention currently as I'm attempting to use TDD for infrastructure coding with my job so I feel I can contribute a lot towards bringing this project to the next level if you will.  I have a strong infrastructure/systems and programming background so I understand all aspects of this type of project in depth.

**Comment by zpatten** [comment]
So I've given up on working on this repo of the project; the un-responsiveness is a bit absurd considering Atalanta has claim the project is "live".  At this point I am forking and pushing my changes into the fork.  I'll update when I've gotten everything in place so you can see what I've done.

**Comment by patcon** [comment]
That unfortunate man, but I understand -- it's tough when people you want to collaborate with aren't in sync in terms of pace, but it happens.

Would you mind humoring me with relaunching the repo so it shows up in the network graph? That way, interested parties can at least see that you're the most active contributor should they be evaluating testing options for chef.

**Comment by zpatten** [comment]
Ya I've sync'd it up show it shows in the network graph.  If I can get some permissions with this repo I'll be happy to merge things back upstream once I have my branch stable.

**Comment by patcon** [comment]
Sahweet. Thanks dude :)

**Comment by Atalanta** [comment]
Zac and I and now in sync and working on this stuff.  If you want to help that would be super awesome.

**Comment by Atalanta** [comment]
(and by the way, I am _totally_ absurd)

**Comment by patcon** [comment]
haha I will definitely stay on top of the discussion as much as I can, and see what I can do. Feel free to //cc @-mention me on any high-level or meta discussions :)

Thanks!

**Comment by zpatten** [comment]
Definitely; any and all help is welcome!  (I am also _totally_ absurd myself :grin:)

**Comment by patcon** [comment]
TEAM WORK: ACTIVATE! I feel this is appropriate:

![Animals Working Together for Internet Flag.](http://oldloft.com/wp-content/themes/oldloft/images/team.png)
