### ISSUE TITLE
chef setup fails on project phase with key issue

### ISSUE THREAD

**Issue by glenndavy** [Atalanta/cucumber-chef#52]
Hi
Following along in the book, and at point of trying to get cucumber-chef setup running.

It provisions just fine, then when it gets to the cucumber-chef setup phase, fails with Permission Denied error (Errno::EACCES). 

It appears to be trying to connect with the key baked into the gem instead of the one specified in knife.
glenn/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/cucumber-chef-1.0.3/cookbooks/cucumber-chef/files/default/cucumber-private-key

I can connect fine manually using ssh and the key specified in the knife config.

Ironically, even though the project test lab hasn't been able to setup, any attempt to create another before terminating the instance, results in  'A test lab already exists using the AWS credentials you supplied'

Any ideas what i might need to do?

Thanks
Here's my knife.rb incase you see any issues:

```
current_dir = File.dirname(__FILE__)
user = ENV['OPSCODE_USER'] || ENV['USER']
log_level                :info
log_location             STDOUT
node_name                "glenndavy"
client_key               "#{ENV['HOME']}/.chef/#{user}.pem"
validation_client_name   "#{ENV['ORGNAME']}-validator"
validation_key           "#{ENV['HOME']}/.chef/#{ENV['ORGNAME']}-validator.pem"
chef_server_url          "https://api.opscode.com/organizations/#{ENV['ORGNAME']}"
cache_type               'BasicFile'
cache_options( :path => "#{ENV['HOME']}/.chef/checksums" )
cookbook_path            ["#{current_dir}/../cookbooks"]


knife[:aws_access_key_id]     = ENV['AWS_ACCESS_KEY_ID']
knife[:aws_secret_access_key] = ENV['AWS_SECRET_ACCESS_KEY']
knife[:identity_file]         = "/Users/glenn/.ssh/tdd-eg.pem"
knife[:aws_ssh_key_id]        = "tdd-eg" #ENV['AWS_SSH_KEY_ID]'
knife[:availability_zone]     = "us-east-1e"
knife[:region]                = "us-east-1"
knife[:aws_image_id]          = "ami-0493486d"
#knife[:ssh_user] = 'ubuntu'
```

**Comment by zpatten** [comment]
your identity file and client key should have the same value, also your aws_ssh_key_id should be the filename minus the extension of your pem:

``` ruby
client_key                    "#{ENV['HOME']}/.chef/#{user}.pem"
knife[:aws_ssh_key_id]        = user
knife[:identity_file]         = "#{ENV['HOME']}/.chef/#{user}.pem"
```

**Comment by glenndavy** [comment]
Thanks for replying zpatten

ok I'm a bit confused at this point, my client key is for the opscode account and the pem file downloaded there, the knife[:identity_file] and knife[:aws_ssh_key_id] file deal with the amazon account and the pem file down loaded there. Is that not right? I don't follow why they'd be the same.

**Comment by zpatten** [comment]
Correction: Sorry in my hasty response I posted incorrect information; aws_ssh_key_id should be the name of the key pair you created in your AWS zone minus the '.pem';  set this in the AWS_SSH_KEY_ID environment variable.

If you named your AWS key pair 'cucumber-chef-us-east-1.pem' then for example:
Put your AWS key pair in your home '.chef' directory, for example: '~/.chef/cucumber-chef-us-east-1.pem'

Make sure you export the details and add the keypair to your ssh-agent via your '.bash_profile' for example:

``` bash
export AWS_SSH_KEY_ID='cucumber-chef-us-east-1'
ssh-add ~/.chef/cucumber-chef-us-east-1.pem
```

Make sure you change your knife config to use the environment variable: 

``` ruby
knife[:aws_ssh_key_id] = ENV['AWS_SSH_KEY_ID']
```

**Comment by glenndavy** [comment]
hey zpatten
No worries, and thanks.. so 
this:
" aws_ssh_key_id should be the name of the key pair you created in your AWS zone minus the '.pem'"
is already the case.

this isn't:
"set this in the AWS_SSH_KEY_ID environment variable."

nor this:
"Put your AWS key pair in your home '.chef' directory, for example: '~/.chef/cucumber-chef-us-east-1.pem'"

I'll try each of these separately and see how it goes.
Thanks

**Comment by glenndavy** [comment]
Ok, so having set aws_ssh_key_id in bash:

```
env |grep AWS                                                                                      
AWS_SSH_KEY_ID=tdd-eg                                                                                                        
AWS_SECRET_ACCESS_KEY=xxxx                              
AWS_ACCESS_KEY_ID=yyyy
```

Added the key to the agent:

```
ssh-add -l  |grep tdd
2048 b3:d7:65:da:f4:b1:f3:de:00:fd:e5:1e:0f:ab:e0:d8 /Users/glenn/.chef/tdd-eg.pem (RSA)
```

relocated the key file to ~/.chef and picking key id up from env:

```
knife[:identity_file]         = "/Users/glenn/.chef/tdd-eg.pem"  
knife[:aws_ssh_key_id]  = ENV['AWS_SSH_KEY_ID']  
```

It still seems a smell to me that the failure occurs while trying to use a private key that is part of the cucumber-chef repo. Just for kicks i changed region to ireland as thats the one the book uses and used the ami quoted in the source code jic there is some majik baked in, but alas still hitting same issue.

keen to hear any other thoughts.

**Comment by zpatten** [comment]
So the key pair is tied to the region you created it in; when you look at the instance in AWS; does it show 'tdd-eg' in the "Key Pair Name" for the instance cucumber-chef has created?

**Comment by glenndavy** [comment]
correct, it does. I can also login using ssh -i ~/.chef/tdd-eg.pem ubuntu@...

**Comment by zpatten** [comment]
I'm at a loss; mine repo is working; but I've re-written about half of this code at this point; I'm in the process of getting everything up in my repo; if you want to give my code a try once I've got it in place (should be a day or two).  I've found a pile of issues and bugs that i've fixed; so at this point my version has diverged pretty far from this.

**Comment by zpatten** [comment]
Just as a stab in the dark; make sure you check the user:group and perms of all the files involved.

**Comment by glenndavy** [comment]
re perms, good call, but already checked.

re using divergent code; yeah no hurry, happy to wait.

**Comment by Atalanta** [comment]
OK - we have an RC now.  Test ALL THE THINGS.  You are teh winner.

**Comment by glenndavy** [comment]
Hey thanks for all you're help, just revisited this.. all is good now.

**Comment by zpatten** [comment]
Awesome, good to hear; thanks for the feedback!
