### ISSUE TITLE
New *active* fork of cucumber-chef

### ISSUE THREAD

**Issue by zpatten** [Atalanta/cucumber-chef#53]
I have been reworking some major parts of cucumber-chef along with fixing various issues.  Since Atalanta appears to not maintain this project with any regularity I will not be pushing pull request to this repo since, if you look at the history over the past 8 months, most pull requests sit in limbo.  That being said I will ultimately be changing the name of my project so I can actually push the gem out via rubygems unless Atalanta wants to give me the rights to publish the cucumber-chef gem on rubygems.

I have things working at this point; but it's not quite in at the stage to be distributed.  Feel free to play around with my fork of the project; feed back is certainly welcome.

https://github.com/zpatten/cucumber-chef

https://github.com/zpatten/cucumber-chef/compare/master

**Comment by Atalanta** [comment]
Very happy to give you publishing rights, and I have every intention of being much more involved again shortly.  Thanks for the note and the activity.

**Comment by zpatten** [comment]
Sounds good to me; I'm about to go on vacation for two weeks so I won't be very active on the fork during this time.  What do I need to do to get the ball rolling on this?  Do you have a preferred email I should contact you at?  I would like to have the ability to make some things happen by the time I get back.

**Comment by Atalanta** [comment]
Great to meet you today at Chefconf.  I've added you as a collaborator.  We can sort out Rubygems stuff shortly.  As suggested I think I'll try to head into town and hang out with you tomorrow night.

**Comment by zpatten** [comment]
Indeed Stephen, it was great talking with you and the Opscode crew at ChefConf today.  I'm looking forward to hanging out with you and it also sounded like some of the Opscode crew will be coming up as well.  Stephen D at Opscode has my contact details and, as I extended to him, you guys are welcome to head up early if you want to see our offices, grab some lunch/dinner, etc.  I'm very excited about the many changes we touched on for the future of cucumber-chef.

**Comment by Atalanta** [comment]
So I will definitely come up this evening.  Stephen and Dan are up for it too. What time is best for you?  I can't leave until 5 at the earliest.

**Comment by zpatten** [comment]
I can take off at anytime, grab my number from Stephen and ping me or just have him give me a call.

**Comment by Atalanta** [comment]
Sorry Zac, things got super delayed last night.  If you're available today that would be great. I can either come to you straight after my Testing Roundtable, or if you would like to come to that we can definitely make room for you.

**Comment by zpatten** [comment]
No worries; worked cleared me to head out for the roundtable so I will try to get there a bit before it starts.  Not sure if you got my text messages or not, sometimes they don't go through for international numbers for some reason.  I'll send you another text via my Google Voice just in case you don't see this in time.

**Comment by Atalanta** [comment]
Zac is a jerk and I won't work with him.  Closing.

JOKE

Zac rocks.  We're on it.
