### ISSUE TITLE
Restore intelligent config file finding

### ISSUE THREAD

**Issue by Atalanta** [Atalanta/cucumber-chef#55]
1.x had intelligent config file finding, which looked iteratively up the filesystem, before defaulting to ~/.chef/knife.rb

2.x has no such feature, which means that cucumber-chef needs to be run from the same directory as the config file.

It would be nice if 2.x looked for config.rb in the same way.

**Comment by zpatten** [comment]
This has been fixed in 2.0.0.rc1
