### ISSUE TITLE
Bogus files created on cucumber-chef project

### ISSUE THREAD

**Issue by Atalanta** [Atalanta/cucumber-chef#56]
Running `cucumber-chef project`, the Thor task generates the example features, readme and steps.  However it also creates two bogus files in the current working directory:

$ tree
.
├── foo
│   ├── README
│   └── features
│       ├── example.feature
│       ├── step_definitions
│       │   └── example_step.rb
│       └── support
│           └── env.rb
├── foofeaturesstep_definitions
└── foofeaturessupport

The last two files are bogus.

**Comment by zpatten** [comment]
This has been fixed in 2.0.0.rc1
