### ISSUE TITLE
Issue with setup task

### ISSUE THREAD

**Issue by Atalanta** [Atalanta/cucumber-chef#57]
Brians-MacBook-Pro:cucumber-chef bhenerey$ cucumber-chef setup
Provisioning cucumber-chef test lab platform.
## Waiting for instance...OK!

Instance ID: i-8a4ba9f3
State: running
Username: ubuntu
IP Address:
  Public...: 50.16.90.218
  Private..: 10.190.101.78
DNS:
  Public...: ec2-50-16-90-218.compute-1.amazonaws.com
  Private..: ip-10-190-101-78.ec2.internal
Tags:
  cucumber-chef: user
##   purpose: cucumber-chef

run(/Users/bhenerey/.rvm/gems/ruby-1.9.3-p194@cucumber-chef/bin/knife
 search node "tags:user AND name:cucumber-chef*" -a name -F json -c /Users/bhenerey/chef-repo/cucumber-chef/.cucumber-chef/knife.rb  --color -n 2>&1) failed! [pid 95541 exit 127]
[01/06/2012 14:54:30] Brian Henerey: looking for knife.rb which it should be looking for config.rb

**Comment by zpatten** [comment]
Actually at this point it should be looking for the knife.rb that is downloaded from the test lab automatically after the bootstrapping process is complete.  This indicates that the bootstrap failed.  There should be a lot of other debug output between this error and the line "purpose: cucumber-chef".  Can you please supply this?

**Comment by zpatten** [comment]
Also the commands themselves, as it stands now, are meant to be run inside the root of the chef-repo and not inside the directory "cucumber-chef" under the chef-repo, which holds the features and steps.  As Stephen mentions in another issue we will be putting some "detection" logic back in to avoid this issue in the future.

**Comment by zpatten** [comment]
Some more context; it's looking for `.cucumber-chef/knife.rb` under your PWD.  This should be the knife.rb downloaded from the private chef server built on the test lab.  This is placed in the `.cucumber-chef` directory and not in the `.chef` directory so it doesn't step on your real `knife.rb`.  It holds the credentials for the `cc-knife` command; which runs knife, but points it at that configuration so you can run against the test lab's chef server.

**Comment by zpatten** [comment]
This has been fixed in 2.0.0.rc1; please pull the latest development version to verify.

**Comment by Atalanta** [comment]
Fixed
