### ISSUE TITLE
Unclean exit from cc-knife

### ISSUE THREAD

**Issue by Atalanta** [Atalanta/cucumber-chef#59]
sns@tdi:~/chef-repo/cookbooks$ cc-knife node list
cc-knife v2.0.0.rc1
/usr/bin/env knife node list -s http://54.247.15.40:4000 -c /home/sns/chef-repo/.cucumber-chef/knife.rb 2>&1
  cucumber-chef.test-lab
  wonderstuff
/home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/cucumber-chef-2.0.0.rc1/bin/cc-knife:23:in `exit': can't convert Process::Status into Integer (TypeError)
    from /home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/cucumber-chef-2.0.0.rc1/bin/cc-knife:23:in`<top (required)>'
    from /home/sns/.rbenv/versions/1.9.3-p194/bin/cc-knife:23:in `load'
    from /home/sns/.rbenv/versions/1.9.3-p194/bin/cc-knife:23:in`<main>'
sns@tdi:~/chef-repo/cookbooks$ cc-knife node show wonderstuff
cc-knife v2.0.0.rc1
/usr/bin/env knife node show wonderstuff -s http://54.247.15.40:4000 -c /home/sns/chef-repo/.cucumber-chef/knife.rb 2>&1
Node Name:   wonderstuff
Environment: _default
FQDN:        wonderstuff
IP:          192.168.187.58
Run List:  
Roles:  
Recipes:  
Platform:    ubuntu 10.04
/home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/cucumber-chef-2.0.0.rc1/bin/cc-knife:23:in `exit': can't convert Process::Status into Integer (TypeError)
    from /home/sns/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/cucumber-chef-2.0.0.rc1/bin/cc-knife:23:in`<top (required)>'
    from /home/sns/.rbenv/versions/1.9.3-p194/bin/cc-knife:23:in `load'
    from /home/sns/.rbenv/versions/1.9.3-p194/bin/cc-knife:23:in`<main>'

**Comment by Atalanta** [comment]
[17/06/2012 21:53:14] Zachary Patten: hmmm
[17/06/2012 21:54:03] Zachary Patten: that's weird
[17/06/2012 21:54:09] Zachary Patten: it's just doing exit(&?)
[17/06/2012 21:54:24] Zachary Patten: guess under 1.9.3 that's not just an integer
[17/06/2012 21:54:34] Stephen Nelson-Smith: what did you t est with
[17/06/2012 21:54:38] Stephen Nelson-Smith: shall i install 1.9.2?
[17/06/2012 21:55:26] Zachary Patten: i've used REE 1.8.7-latest and 1.9.2

**Comment by kaii-zen** [comment]
I get the same behavior on 1.9.2:

```
cc-knife v2.0.0.rc1
/usr/bin/env knife node list -s http://50.16.116.64:4000 -c /Users/shayb/chef-repo/.cucumber-chef/knife.rb 2>&1
cucumber-chef.test-lab
/Users/shayb/.rvm/gems/ruby-1.9.2-p320@chef/gems/cucumber-chef-2.0.0.rc1/bin/cc-knife:23:in `exit': can't convert Process::Status into Integer (TypeError)
    from /Users/shayb/.rvm/gems/ruby-1.9.2-p320@chef/gems/cucumber-chef-2.0.0.rc1/bin/cc-knife:23:in `<top (required)>'
    from /Users/shayb/.rvm/gems/ruby-1.9.2-p320@chef/bin/cc-knife:19:in `load'
    from /Users/shayb/.rvm/gems/ruby-1.9.2-p320@chef/bin/cc-knife:19:in `<main>'
    from /Users/shayb/.rvm/gems/ruby-1.9.2-p320@chef/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/shayb/.rvm/gems/ruby-1.9.2-p320@chef/bin/ruby_noexec_wrapper:14:in `<main>'
```

Apparently changing from exit($?) to exit($?.to_i) solves this.

**Comment by zpatten** [comment]
Thanks for the info; ya from what I saw under the 1.9.3 crash report, '$?' is returning an object.  Let me try to reproduce under 1.9.2.

**Comment by zpatten** [comment]
Ya I must of missed this under 1.9.2;  looks like that ruby version and higher returns a `Process::Status`.

**Comment by zpatten** [comment]
OK; I've push the fix to the RC branch.  Please feel free to reopen the issue if this change has not resolved things.
