### ISSUE TITLE
Could not find readme.erb when creating a project

### ISSUE THREAD

**Issue by mikehale** [Atalanta/cucumber-chef#6]
When running this command:
`cucumber-chef project cucumber-chef-project`

I get this error:
Could not find "~/.rvm/gems/ruby-1.9.2-p180/gems/cucumber-chef-1.0.0/lib/cucumber/chef/templates/readme.erb" in any of your source paths.
 Please invoke CucumberChef.source_root(PATH) with the PATH containing your templates. Currently you have no source paths.

**Comment by fnichol** [comment]
I see the same thing with the same ruby release (RVM'd).

**Comment by mtnygard** [comment]
I'm getting this on "example_step.erb" instead of "readme.erb". Same error otherwise, though.  I'm also using RVM.

**Comment by Atalanta** [comment]
Fixed, will release shortly.
