### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by jperry** [Atalanta/cucumber-chef#60]
Hey guys,

So I am super interested in tying this into continuous delivery with a CI server.  Any thoughts on the type of workflow you suggest using chef server to promote your changes.  I'm trying to map out the best workflow that will work with continuous delivery of our infrastructure code.

Thanks,
Jay

**Comment by zpatten** [comment]
I can't say that I have any sort of best workflow yet.  Our plan at my work is to do the same thing.  We are using Janky/Jenkins; but we haven't tackled the integration of it just yet.  I will be sure to share my experiences on it, we're set to tackle this soon.

**Comment by zpatten** [comment]
@jperry I believe this is very doable now if you want to continue this discussion.

**Comment by jperry** [comment]
@zpatten - I've actually implemented a whole workflow using minitest-handler and vagrant.  It has been working very well but now that cucumber-chef is now working with vagrant I may revisit using cucumber-chef in our next iteration of our workflow.  I hope to write a blog post on the workflow we are using, when I do I'll post to this issue.  Thanks for following up.

**Comment by zpatten** [comment]
@jperry Awesome!  I would be interested to hear about that!

I will be working on a Cucumber-Chef CI workflow for my company in the near future and definitely want minitest in the mix.

**Comment by zpatten** [comment]
Closing this out for now.
