### ISSUE TITLE
Problem with ssh keys

### ISSUE THREAD

**Issue by pikesley** [Atalanta/cucumber-chef#63]
Hi

I've encountered a bug in the `cucumber-chef setup` step: it started up OK, but then sat at the `Bootstrapping AWS EC2 instance...` step forever (I killed it after an hour).

I eventually discovered (after trying to restart the previously-stalled instance) the problem:

```
Downloading container SSH credentials...//Users/sam/.rvm/gems/ruby-1.9.2-p320@cuke-chef/gems/net-sftp-2.0.5/lib/net/sftp/operations/download.rb:307:in `on_open': open /home/ubuntu/.ssh/id_rsa: no such file (2) (RuntimeError)
```

Aha! So I jumped on the box and did a bit of `ssh-keygen`, ran setup again, and now it works.

This was using cucumber-chef-2.0.1.pre on my 10.6 Mac.

Anybody else come across this?

Sam

**Comment by zpatten** [comment]
About 1 out of 20 times for me it hangs on the bootstrapping.  I've found tailing the log file so you can see the output from what is running on the server helps.  At least you can tell if it's hung or if it's chugging along provisioning.  My gut feeling says it's likely an issue in Fog.

Also if it didn't generate the keys; it's very, very likely other test-lab configuration bits in the chef cookbooks did not run during provisioning.  You might want to re-build your test-lab.

All the more reason to get virtualbox/vagrant support going in my mind.

**Comment by pikesley** [comment]
Vagrant, yes please :)

**Comment by pikesley** [comment]
Just ran up a test lab with 2.0.2.pre and it worked first time (this had _never_ worked for me with 2.0.1, I always had to interfere at the ssh-keygen step and restart the setup). Awesome, thanks :)

**Comment by zpatten** [comment]
Great to hear!  Thanks again for testing this @pikesley !

**Comment by c10l** [comment]
I'm having this exact same problem using 2.0.3. Tailing the cucumber-chef log file doesn't help much since it sends the whole bootstrap process in `2012-09-13 20:55:00.005815 |  8871 |  INFO | ssh.rb:69:exec | command(sudo bash -c ' ... )`.

Is there a logfile I can tail on the test lab box to better understand where the problem is happening?

**Comment by pikesley** [comment]
Presuming you can get on the test lab box, the logs you want are in `/var/log/chef/` I think

**Comment by c10l** [comment]
Yes, that was it. I had looked for it, but apparently it hadn't been created yet. :)

It seems like my issue is pure misconfiguration on my part, not a bug.

Thanks!
