### ISSUE TITLE
I must be doing something wrong

### ISSUE THREAD

**Issue by pikesley** [Atalanta/cucumber-chef#64]
Hi

I have an idea for an enhancement, so I've checked out my fork and am running it with e.g. `bundle exec bin/cucumber-chef test`. The output I see is 

```
$ bundle exec bin/cucumber-chef test
cucumber-chef v2.0.1.patch

Using features directory: /Users/sam/cuke-chef/features
Cucumber-Chef Test Runner Initalized!
Cleaning up any previous test runs...done.
Uploading files required for this test run...done.
Executing Cucumber-Chef Test Runner
@teamserver
Feature: Tech team members can log into team server

  Background:                                                                 # ./teamserver/teamserver.feature:4
  >>> servers are being preserved
    * I have a server called "teamserver"                                     # cucumber-chef-2.0.1/lib/cucumber/chef/steps/provision_steps.rb:22
    * "teamserver" should be persistant                                       # cucumber-chef-2.0.1.pre/lib/cucumber/chef/steps/provision_steps.rb:34
    * "teamserver" is running "ubuntu" "lucid"                                # cucumber-chef-2.0.1.pre/lib/cucumber/chef/steps/provision_steps.rb:26
    * "teamserver" has been provisioned                                       # cucumber-chef-2.0.1.pre/lib/cucumber/chef/steps/provision_steps.rb:46
etc, etc
```

I've changed the version string (so I get `cucumber-chef v2.0.1.patch` at the top there) but then I get `cucumber-chef-2.0.1.pre/lib/cucumber/chef/steps/provision_steps.rb:22` and so on. I've tried editing those lines in my working repo - I've inserted blanks to change the line numbers, I've even commented out that whole _provision_steps.rb_ file - and I still get _exactly_ the same output. It's clearly not touching my local code at all. I have no references to _2.0.1.pre_ anywhere. The cucumber-chef gem is not installed in this gemset. Where the hell is that coming from? It's like it's cached somewhere.

Chances are, I'm doing something extremely dumb (I'm definitely more Ops than Dev), but has anybody got any ideas please? This enhancement will be _awesome_, promise :)

Sam

**Comment by zpatten** [comment]
You need to build your modified gem and install it on the test lab; don't forget to remove the pre release version when doing this.  Also with binstubs you do not need to use `bundle exec`.

**Comment by pikesley** [comment]
Oh of course. It was me being dumb then. It occurs to me, though, isn't this going to result in a painfully long dev cycle?

**Comment by zpatten** [comment]
Not really.  I just wrote a script to build the gem and push it into my "testing" test lab.  The majority of the code executes locally as is; it's only when dealing with the cuke helpers can things get a bit annoying due to that.  I have plans to shift around the way some of the internals work related to LXC and how the test lab communication is handled, which should result with a minimal footprint in the test lab with the cukes executing locally (instead of on the test lab as is the case now).

**Comment by zpatten** [comment]
I've included a binary script with the latest 2.0.2.pre release for pushing the gem up into the test lab when doing development.  Please feel free to test this out and let me know how it works for you.

**Comment by pikesley** [comment]
Yes, I can confirm this works! Awesome, thanks dude. Pull requests coming soon, I suspect...

**Comment by zpatten** [comment]
Awsome; thank you for testing @pikesley !
