### ISSUE TITLE
features directory being created in ~/ not ./

### ISSUE THREAD

**Issue by glenndavy** [Atalanta/cucumber-chef#66]
Using 2.0.1pre this:

```
cd ~/my-repo
cucumber-chef create new_project
```

creates "~/features/new_project" not "~/my-repo/features/new_project"

Any thoughts how I might have caused this behaviour?

Thanks

**Comment by zpatten** [comment]
As is it scans for the `.chef` directory.  My guess is you don't have a `.chef` directory off your `chef-repo`, but under your home directory?

**Comment by glenndavy** [comment]
yeah good guess :facepalm:

thanks
