### ISSUE TITLE
chef_environments

### ISSUE THREAD

**Issue by pikesley** [Atalanta/cucumber-chef#68]
Not so much an issue, more a possibly-useful hack: https://gist.github.com/3360194

**Comment by zpatten** [comment]
Nice; I would prefer a pull request; but that's pretty light so I'll see about getting it plugged in.

**Comment by zpatten** [comment]
I've got a new release out with environment support; the chef steps on the Wiki have been update with usage.  Can you please test and confirm?

**Comment by pikesley** [comment]
Wow, yes this works, thank you so much, this will make everything much slicker over here now :)
