### ISSUE TITLE
Multi-line string matches

### ISSUE THREAD

**Issue by pikesley** [Atalanta/cucumber-chef#77]
This may be a bit of a stretch, but here goes: I'd really like to be able to write features like this:

```
* file "/etc/nginx/sites-available/foo.bar.com" should contain
  """
  listen 80;
  server_name foo.bar.com;"
  """
```

(as an alternative to something like `... should contain "listen 80;\n *server_name foo.bar.com;"` which works but is really cumbersome). I worked out a suitable regex in rubular (which worked fine there), and put it into ssh_steps thus:

```
Then /^file "([^\"]*)" should( not)? contain\n? *(?:"")?"([^\"]*)"(?:"")?$/ do |path, boolean, content|
```

but cuke-chef, running against the above feature, didn't seem to find that at all:

```
You can implement step definitions for undefined steps with these snippets:

Given /^file "(.*?)" should contain$/ do |arg1, string|
  pending # express the regexp above with the code you wish you had
end
```

Maybe I'm trying to bend the tool beyond its limits here, but this would be really nice.

This is an attempt to extend my work in [this commit](https://github.com/pikesley/cucumber-chef/commit/a6504421746d2b22fa18d48839c0179c9dc7d930)

**Comment by zpatten** [comment]
I think this is a great idea.  It does technically go beyond the scope of the gem, but I think having a nice solid set of out-of-the-box-ready-to-go steps is a win all around.
