### ISSUE TITLE
Deprecate 1.x

### ISSUE THREAD

**Issue by Atalanta** [Atalanta/cucumber-chef#80]
I think we should release 2.0 ASAP, and publicly deprecate 1.x

Much too much has changed, and we don't maintain 1.x at all.

Right now the standard punter running gem install will get old, buggy and unmaintained code.

**Comment by pikesley** [comment]
Yes, except the book seems to be all based on 1.0. This would basically deprecate the book, wouldn't it?

**Comment by zpatten** [comment]
:+1:

**Comment by zpatten** [comment]
I've released 2.0.3 fully now.

**Comment by Atalanta** [comment]
2nd edition of the book will be out very soon indeed, and is all based on 2.0
