### ISSUE TITLE
Example feature doesn't pass.

### ISSUE THREAD

**Issue by Dao007forever** [Atalanta/cucumber-chef#85]
Hi,

I follow the steps in the wiki but the example still throws some errors.

Failing Scenarios:
cucumber ./devopserver/devopserver.feature:17 # Scenario: Can connect to the provisioned server via SSH authentication

It seems like the ssh failed:

` I ssh to "devopserver" with the following credentials:                         # cucumber-chef-2.0.4/lib/cucumber/chef/steps/ssh_steps.rb:57
      | username | keyfile     |
      | root     | ../.ssh/id_rsa |

```
  exit (SystemExit)
  /home/ubuntu/features/support/env.rb:50:in \`exit'
  /home/ubuntu/features/support/env.rb:50:in \`After'`
```

When I tried to ssh into the instance, it says:

`Attempting SSH connection to cucumber-chef container 'devopsrver'...
nc: getaddrinfo: Name or service not known`

Best regards,
Trong Dao.

**Comment by zpatten** [comment]
Sorry for the delay; this should be fixed in the latest release.

**Comment by Dao007forever** [comment]
Thanks :+1:

**Comment by zpatten** [comment]
Closing
