### ISSUE TITLE
Could not find task "test"

### ISSUE THREAD

**Issue by anujbiyani** [Atalanta/cucumber-chef#87]
In order to run tests I gather from the wiki that I'm supposed to run `cucumber-chef test`. Unfortunately, this task seems to not exist in the latest version (2.0.7).

```
$> cucumber-chef test
Could not find task "test".
```

It's also not listed as one of the available options:

```
$> cucumber-chef
Tasks:
  cucumber-chef create <project>      # Create a project template for testing an infrastructure.
  cucumber-chef diagnose <container>  # Provide diagnostics from the chef-client on the specified container.
  cucumber-chef displayconfig         # Display the current cucumber-chef config.
  cucumber-chef down                  # Shutdown the cucumber-chef test lab
  cucumber-chef help [TASK]           # Describe available tasks or one specific task
  cucumber-chef info                  # Display information about the current test lab.
  cucumber-chef init                  # Initalize cucumber-chef configuration
  cucumber-chef ps [ps-options]       # Snapshot of the current cucumber-chef test lab container processes.
  cucumber-chef setup                 # Setup cucumber-chef test lab in Amazon EC2
  cucumber-chef ssh [container]       # SSH to cucumber-chef test lab or [container] if specified.
  cucumber-chef teardown [container]  # Teardown the cucumber-chef test lab in Amazon EC2 or a test lab [container] if specified.
  cucumber-chef up                    # Startup the cucumber-chef test lab
```

Digging through the commit history, I found this commit (https://github.com/Atalanta/cucumber-chef/commit/72f051a607d6d93e0d1db8e71608a86aab4a454e) that removes the test task. Is there a new way to run tests that isn't mentioned in the wiki?

(For now I've switched back to 2.0.4, the last version that seems to have the test task.)

**Comment by gburch** [comment]
I had the same problem. The solution is to just run "cucumber"

**Comment by zpatten** [comment]
Sorry guys; I need to update the documents; you run cucumber directly now; everything runs locally in the latest version.

**Comment by anujbiyani** [comment]
Ah alright; thanks!

**Comment by anujbiyani** [comment]
Actually maybe this issue should be left open until the docs are updated? That way it's visible to anyone else who runs into the same problem.

**Comment by zpatten** [comment]
:+1: I think that's a good idea.

**Comment by anujbiyani** [comment]
Just updated the Wiki with the current way of running tests. Closing this issue now.
