### ISSUE TITLE
gem deps

### ISSUE THREAD

**Issue by nevir** [Atalanta/cucumber-chef#93]
This is pointing to your current master (I'm excited about vagrant support!)

```
Bundler could not find compatible versions for gem "json":
  In Gemfile:
    cucumber-chef (>= 0) ruby depends on
      json (~> 1.5.1) ruby

    chef (~> 10.18.0) ruby depends on
      json (1.6.1)
```

Can you loosen that any?  (Unsure which of your deps are forcing the matter)

**Comment by nevir** [comment]
Never mind, chef `10.18.2` loosened their dependency!

**Comment by zpatten** [comment]
Ya I hit something similar to this issue.  Wasn't sure what it was; dependencies all where within constraints for me (I manually verified); but nuking my Gemfile.lock, resetting my RVM gemset and a `bundle update --binstubs` later I was back in business.

**Comment by zpatten** [comment]
Reopening this so people have better visibility of this issue.
